### ISSUE TITLE
error in RPC call to 'Filecoin.StateMinerInfo': (get ssize) failed to load miner actor state

### ISSUE THREAD

**Issue by ccyanxyz** [pygate/pygate-webapp#7]
I started the app and try to upload a file, but I got this error from the backend:
```
127.0.0.1 - - [04/Aug/2020 14:11:12] "POST /files HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/cyan/.pyenv/versions/3.7.0/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/cyan/.pyenv/versions/3.7.0/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/cyan/.pyenv/versions/3.7.0/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cyan/.pyenv/versions/3.7.0/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/cyan/.pyenv/versions/3.7.0/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cyan/.pyenv/versions/3.7.0/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cyan/.pyenv/versions/3.7.0/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cyan/.pyenv/versions/3.7.0/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/cyan/.pyenv/versions/3.7.0/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cyan/.pyenv/versions/3.7.0/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cyan/Desktop/blockchain/filecoin/pygate-webapp/pygate/routes.py", line 64, in files
    ffs = create_ffs(default=True)
  File "/Users/cyan/Desktop/blockchain/filecoin/pygate-webapp/pygate/helpers.py", line 21, in create_ffs
    ffs = powergate.ffs.create()
  File "/Users/cyan/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pygate_grpc/errors.py", line 19, in wrapper
    raise err_to_raise
pygate_grpc.exceptions.GRPCNotAvailableException
```

I set up my powergate node using the docker release `powergate-docker-v0.3.0.zip` from `https://github.com/textileio/powergate/releases/tag/v0.3.0`, and this is the powergate error log:
```
lotus_1      | 2020-08-04T06:19:19.557Z	WARN	rpc	go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/handler.go:226	error in RPC call to 'Filecoin.StateMinerInfo': (get ssize) failed to load miner actor state:
lotus_1      |     github.com/filecoin-project/lotus/chain/stmgr.StateMinerInfo
lotus_1      |         /go/pkg/mod/github.com/filecoin-project/lotus@v0.4.0/chain/stmgr/utils.go:222
lotus_1      |   - cbor input had wrong number of fields
lotus_1      | 2020-08-04T06:19:19.557Z	WARN	rpc	go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/handler.go:226	error in RPC call to 'Filecoin.StateMinerInfo': (get ssize) failed to load miner actor state:
lotus_1      |     github.com/filecoin-project/lotus/chain/stmgr.StateMinerInfo
lotus_1      |         /go/pkg/mod/github.com/filecoin-project/lotus@v0.4.0/chain/stmgr/utils.go:222
lotus_1      |   - cbor input had wrong number of fields
lotus_1      | 2020-08-04T06:19:19.557Z	WARN	rpc	go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/handler.go:226	error in RPC call to 'Filecoin.StateMinerInfo': (get ssize) failed to load miner actor state:
lotus_1      |     github.com/filecoin-project/lotus/chain/stmgr.StateMinerInfo
lotus_1      |         /go/pkg/mod/github.com/filecoin-project/lotus@v0.4.0/chain/stmgr/utils.go:222
lotus_1      |   - cbor input had wrong number of fields
```

Does anyone know how to solve this? Thanks!

**Comment by apogiatzis** [comment]
@ccyanxyz what filecoin network are you using with powergate setup??? To me it seems that there is something wrong with your powergate setup. Try "localnet" just to make sure that the webapp is working properly and then try setup testnet.

**Comment by ccyanxyz** [comment]
I'm using the powergate 0.3 docker release: https://github.com/textileio/powergate/releases/tag/v0.3.0
download & unzip powergate-docker-v0.3.0.zip, cd to the folder, and start the localnet using this command:
```
BIGSECTORS=true make localnet
```

**Comment by ccyanxyz** [comment]
Problem solved. I forgot to turn off the command line proxy, caused the exception `pygate_grpc.exceptions.GRPCNotAvailableException`.  The `cbor input had wrong number of fields` error log is unrelated to this.
